function readVars() {
bridge_mainLeft_power = 'on';
bridge_mainRight_power = 'on';
bridge_mainCenter_power = 'ff';
bridge_foldbackCenter_power = 'xoff';
chapel_mainSide_power = 'off';
chapel_mainCenter_power = 'off';
chapel_foldbackSide_power = 'off';
gym_mainSide_power = 'off';
well_mainCenter_power = 'off';
rm101A_mainCenter_power = 'GEEK_ERR';
rm101C_mainCenter_power = 'GEEK_ERR';
rm102_mainCenter_power = 'off';
rm104_mainCenter_power = 'off';
rm128_mainCenter_power = 'off';
rm212_mainCenter_power = 'off';
rm214_mainCenter_power = 'off';
rm216_mainCenter_power = 'off';
rmRR1_mainCenter_power = 'GEEK_ERR';
rmXX_mainCenter_power = 'GEEK_ERR';
}
